name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: cd
      run: cd $GITHUB_WORKSPACE/philo_one
    - name: make
      run: make
    - name: cd
      run: cd $GITHUB_WORKSPACE/philo_two
    - name: make
      run: make
    - name: cd
      run: cd $GITHUB_WORKSPACE/philo_three
    - name: make
      run: make
    

